### ISSUE TITLE
Attic build GitHub Action

### ISSUE THREAD

**Issue by Svenum** [zhaofengli/attic#171]
Hi,
I like to let you know that I am currently working on an GitHub Action to bild a hole Flake (Packages and nixosConfigurations) to push them to you own Attic instance.

So that you can periodically or on every push build your config and cache the result in your Attic Cache.
As I have not much experience with GitHub Actions I appreciate every help form you guys. :smile: 

ULR: https://github.com/Svenum/attic-builder

**Comment by jzbor** [comment]
Hi, I have build something similar with https://github.com/jzbor/nix-flake-workflow. Although this is currently mostly for my personal use and may change over time. But feel free to use it as inspiration or with a pinned commit.

**Comment by cottand** [comment]
my personal approach:

```yaml
env:
  ATTIC_SERVER: "https://my.attic.com/"
  ATTIC_CACHE: "default"

jobs:
  myjob:
   steps:
    - name: Install Attic and nix-fast-build
      shell: bash
      run: |
        nix profile install nixpkgs#attic-client github:Mic92/nix-fast-build/8e7c9d7

    - name: Configure Attic
      shell: bash
      run: |
        attic login --set-default central "$ATTIC_SERVER" "$ATTIC_TOKEN"
        attic use "$ATTIC_CACHE"

      env:
        ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

    - name: Build
      shell: bash
      run: |
        nix-fast-build --eval-workers 1 --skip-cached --no-nom --attic-cache=$ATTIC_CACHE \
            -f .#myPackage

        # OR, ALTERNATIVELY:
        
        nix build .#myPackage
        attic push $ATTIC_CACHE result
   
```

You can package this as a [composite action](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action) (my example [here](https://github.com/cottand/selfhosted/blob/master/.github/workflows/main.yml))

**Comment by Svenum** [comment]
My builder has now reached version 2. with a Docker that can periodically pull an GitHub repo, to build and push the content. https://github.com/Svenum/attic-builder

**Comment by Alxandr** [comment]
I recently published https://github.com/YoloDev/actions-attic v0.1.0. I mirrored how the cachix action work. Simply add this to your github workflow (assuming you have a secret called ATTIC_TOKEN):

```yaml
      - uses: YoloDev/actions-attic@7a1c97712ee0e9953a06181473792f2ed318bc82 # v0.1.0
        id: attic
        with:
          server: CHANGE_ME
          cacheName: CHANGE_ME
          token: ${{ secrets.ATTIC_TOKEN }}
```

This will setup attic as a cache for pulling, **and** will push any built packages back to the cache when the workflow is over.
